steps:
- name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
  entrypoint: "bash"
  args: ['gsutil', '-m', 'cp', '-r', '.', 'gs://srcprojectfiles/telecom_customer_data/']
options:
      logging: CLOUD_LOGGING_ONLY
